Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DynamicCMS.Data;
using DynamicCMS.Data.Models;
using DynamicCMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.FileProviders;

namespace DynamicCMS.Controllers
{
	[Authorize]
    public class AssetsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AssetsController(ApplicationDbContext context)
        {
	        _context = context;
        }

        public IActionResult CreateFromProject(int? id)
        {
	        if (id == default(int))
	        {
		        throw new ArgumentNullException("project id is not set");
	        }

	        var asset = new Asset()
	        {
		        ProjectId = id.Value
	        };
	        ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", nameof(Project.Name), id.Value);

	        return View(nameof(Create), asset);
        }

       
        public async Task<IActionResult> Download(string id)  
        {
	        var filePath = id;
	          var memory = new MemoryStream();  
	          using (var stream = new FileStream(filePath, FileMode.Open))  
	          {  
		          await stream.CopyToAsync(memory);  
	          }  
	          memory.Position = 0;  
	          return File(memory, GetContentType(filePath), Path.GetFileName(filePath));  
        } 

        // GET: Assets
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Assets.Include(a => a.Project);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Assets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asset = await _context.Assets
                .Include(a => a.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asset == null)
            {
                return NotFound();
            }

            return View(asset);
        }

        // GET: Assets/Create
        public IActionResult Create()
        {
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", nameof(Project.Name));
            return View();
        }

        // POST: Assets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,FilePath,ProjectId,Id")] Asset asset)
        {
            if (ModelState.IsValid)
            {
	            _context.Add(asset);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Upload), new { id = asset.Id });
            }

            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", nameof(Project.Name), asset.ProjectId);
            return View(asset);
        }

        private Asset UploadFile(AssetViewModel model)
        {
	        var files = model.Files;
	        string filepath = string.Empty;

	        if (files != null)
	        {
		        if (files.Length > 0)
		        {
			        //Getting FileName
			        var fileName = Path.GetFileName(files.FileName);

			        //Assigning Unique Filename (Guid)
			        var myUniqueFileName = model.Name;

			        //Getting file Extension
			        var fileExtension = Path.GetExtension(fileName);

			        // concatenating  FileName + FileExtension
			        var newFileName = String.Concat(myUniqueFileName, fileExtension);

			        // Combines two strings into a path.
			        filepath =
				        new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "assets")).Root + $@"\{newFileName}";

			        using (FileStream fs = System.IO.File.Create(filepath))
			        {
				        files.CopyTo(fs);
				        fs.Flush();
			        }
		        }
	        }

			var asset = new Asset()
			{
				Id = model.Id,
				FilePath = filepath,
				Name = model.Name,
				ProjectId = model.ProjectId
			};
			return asset;
		}

        // GET: Assets/Edit/5
        public async Task<IActionResult> Upload(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asset = await _context.Assets.FindAsync(id);
            if (asset == null)
            {
                return NotFound();
            }

            var assetViewModel = new AssetViewModel()
            {
	            Id = asset.Id,
	            FilePath = asset.FilePath,
	            Name = asset.Name,
	            ProjectId = asset.ProjectId
            };

            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", nameof(Project.Name), assetViewModel.ProjectId);
            return View(assetViewModel);
        }

		//POST: Assets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Upload(int id, [Bind("Name,FilePath,Files,ProjectId,Id")] AssetViewModel model)
		{
			if (id != model.Id)
			{
				return NotFound();
			}

			if (!ModelState.IsValid)
			{
				ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", nameof(Project.Name), model.ProjectId);
				return View(model);
			}

			try
			{
                RemvoeFileIfExist(model.FilePath);
                var asset = UploadFile(model);

				_context.Update(asset);
				await _context.SaveChangesAsync();
			}
			catch (DbUpdateConcurrencyException)
			{
				if (!AssetExists(model.Id))
				{
					return NotFound();
				}
				else
				{
					throw;
				}
			}
			return RedirectToAction(nameof(Index));
		}

		// GET: Assets/Delete/5
		public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asset = await _context.Assets
                .Include(a => a.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asset == null)
            {
                return NotFound();
            }

            return View(asset);
        }

        // POST: Assets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var asset = await _context.Assets.FindAsync(id);

            RemvoeFileIfExist(asset.FilePath);

            _context.Assets.Remove(asset);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private static void RemvoeFileIfExist(string filePath)
        {
	        if (System.IO.File.Exists(filePath))
	        {
		        System.IO.File.Delete(filePath);
	        }
        }

        private bool AssetExists(int id)
        {
            return _context.Assets.Any(e => e.Id == id);
        }
        private string GetContentType(string path)  
        {  
	        var types = GetMimeTypes();  
	        var ext = Path.GetExtension(path).ToLowerInvariant();  
	        return types[ext];  
        }  
   
        private Dictionary<string, string> GetMimeTypes()  
        {  
	        return new Dictionary<string, string>  
	        {  
		        {".txt", "text/plain"},  
		        {".pdf", "application/pdf"},  
		        {".doc", "application/vnd.ms-word"},  
		        {".docx", "application/vnd.ms-word"},  
		        {".xls", "application/vnd.ms-excel"},  
		        {".xlsx", "application/vnd.openxmlformatsofficedocument.spreadsheetml.sheet"},  
		        {".png", "image/png"},  
		        {".jpg", "image/jpeg"},  
		        {".jpeg", "image/jpeg"},  
		        {".gif", "image/gif"},  
		        {".csv", "text/csv"}  
	        };  
        }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DynamicCMS.Data;
using DynamicCMS.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace DynamicCMS.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProjectsController(
	        ApplicationDbContext context, 
	        UserManager<ApplicationUser> userManager)
        {
	        _context = context;
	        _userManager = userManager;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Projects.Include(p => p.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(p => p.User)
                .Include(m => m.UnityAssets)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
	        var userId = _userManager.GetUserId(User);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", nameof(ApplicationUser.UserName));
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,UserId,Id")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", nameof(ApplicationUser.UserName), project.UserId);
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", nameof(ApplicationUser.UserName), project.UserId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,UserId,Id")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", nameof(ApplicationUser.UserName), project.UserId);
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.Projects.FindAsync(id);
            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Projects.Any(e => e.Id == id);
        }
    }
}

Views/Projects/Create.cshtml
@model DynamicCMS.Data.Models.Project

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Projects/Delete.cshtml
@model DynamicCMS.Data.Models.Project

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Projects/Details.cshtml
@model DynamicCMS.Data.Models.Project

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserName)
        </dd>
    </dl>
    
    <p>
        <a asp-controller="Assets" asp-action="CreateFromProject" asp-route-Id="@Model.Id">Create Unity Assets</a>
    </p>
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UnityAssets[0].Name)
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.UnityAssets)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-controller="Assets" asp-action="Upload" asp-route-id="@item.Id">Upload</a> |
                    <a asp-controller="Assets" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="Assets" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Projects/Edit.cshtml
@model DynamicCMS.Data.Models.Project

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Projects/Index.cshtml
@model IEnumerable<DynamicCMS.Data.Models.Project>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New Project</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.UserName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>